Switch to std::io::{Error,Result}
The error struct defined by the udev crate doesn't really seem to add
any value over simply using std::io::Error directly and doesn't give
great error messages either.

Switch over to simply using std::io:Error directly as well as changing
the try_alloc! over to get the value of errno rather then always
returning ENOMEM on failure.

When debugging the failure of creating monitoring sockets this changed
the error reporting from:
  Error: Custom { kind: Other, error: "Unknown error -12" }
to:
  Error: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }

Which is a lot more meaningful.

Signed-off-by: Sjoerd Simons <sjoerd.simons@collabora.co.uk>